### ISSUE TITLE
安装及运行报错

### ISSUE THREAD

**Issue by UPCzpc** [xumi1993/SplitRFLab#3]
我在 install_SplitLab和search earthquakes时各报了一个错误，
希望您能抽空帮忙解决下。
![4](https://user-images.githubusercontent.com/38318192/39281252-47b497ee-4936-11e8-9e81-83dc2909c33a.png)
![5](https://user-images.githubusercontent.com/38318192/39281253-47fb7204-4936-11e8-991a-3af9258cb553.png)

**Comment by xumi1993** [comment]
1. Pls ignore this error raised on Linux
2. Pls re-install processRFmatlab

**Comment by UPCzpc** [comment]
我尝试了重装 但搜索地震时仍然存在图二中的问题，splitlab没有新的弹出窗口和

**Comment by xumi1993** [comment]
Ok, if you tried it, I think you didn’t install Mapping Toolbox when you install matlab.
Pls reinstall Matlab with Mapping Toolbox.
